// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:EducationApp.PresentationLayer.Controllers.AdminController.UpdateUser(EducationApp.BusinessLogicLayer.Models.Users.UserModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:EducationApp.PresentationLayer.Controllers.AdminController.UpdateOtherUser(EducationApp.BusinessLogicLayer.Models.Users.UserModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:EducationApp.PresentationLayer.Controllers.AdminController.Login(EducationApp.BusinessLogicLayer.Models.ViewModels.LoginViewModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:EducationApp.PresentationLayer.Controllers.AdminController.Logout~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:EducationApp.PresentationLayer.Controllers.AdminController.Profile~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:EducationApp.PresentationLayer.Controllers.AdminController.Ban(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:EducationApp.PresentationLayer.Controllers.AccountController.Register(EducationApp.BusinessLogicLayer.Models.Users.UserModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:EducationApp.PresentationLayer.Controllers.AccountController.Login(EducationApp.BusinessLogicLayer.Models.Requests.LoginRequestModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:EducationApp.PresentationLayer.Controllers.AccountController.Logout(EducationApp.BusinessLogicLayer.Models.Requests.ConfirmEmailRequestModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:EducationApp.PresentationLayer.Controllers.AccountController.ConfirmEmail(EducationApp.BusinessLogicLayer.Models.Requests.ConfirmEmailRequestModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:EducationApp.PresentationLayer.Controllers.AccountController.ResetPassword(EducationApp.BusinessLogicLayer.Models.Requests.ResetPasswordRequestModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:EducationApp.PresentationLayer.Controllers.AccountController.RefreshToken(EducationApp.BusinessLogicLayer.Models.TokensModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:EducationApp.PresentationLayer.Controllers.AccountController.ForgotPassword(EducationApp.BusinessLogicLayer.Models.Requests.ForgotPasswordRequestModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:EducationApp.PresentationLayer.Controllers.AccountController.GetUserInfo(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:EducationApp.PresentationLayer.Controllers.AccountController.ChangePassword(EducationApp.BusinessLogicLayer.Models.Requests.ChangePasswordRequestModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:EducationApp.PresentationLayer.Controllers.AccountController.UpdateUser(EducationApp.BusinessLogicLayer.Models.Users.UserModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:EducationApp.PresentationLayer.Controllers.OrderController.ConvertCurrency(EducationApp.BusinessLogicLayer.Models.Requests.CurrencyConvertRequestModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
